import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, Copy, Check, Filter, RotateCcw, FileText, Clock, Coins, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { VibeScoreGauge } from '@/components/ui/VibeScoreGauge';
import { IssueCard } from '@/components/ui/IssueCard';
import { useAnalysisStore } from '@/store/analysisStore';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

type FilterType = 'all' | 'critical' | 'important' | 'nice-to-have';

export default function ResultsPage() {
  const navigate = useNavigate();
  const { repoInfo, priorities, vibeScore, totalTokensUsed, filesScanned, elapsedTime, resetAnalysis } = useAnalysisStore();
  const [filter, setFilter] = useState<FilterType>('all');
  const [copied, setCopied] = useState(false);

  const allIssues = priorities.flatMap((p) => p.issues);
  const filteredIssues = filter === 'all' ? allIssues : allIssues.filter((issue) => issue.severity === filter);

  const formatTime = (seconds: number) => `${Math.floor(seconds / 60)}m ${seconds % 60}s`;

  const generateMarkdown = () => {
    const date = new Date().toISOString().split('T')[0];
    let md = `# CodeVibes Analysis Report\n\n**Repository:** ${repoInfo?.fullName || 'Unknown'}\n**Date:** ${date}\n**Score:** ${vibeScore}/100\n**Files:** ${filesScanned}\n**Tokens:** ${totalTokensUsed.toLocaleString()}\n\n---\n\n`;

    const critical = allIssues.filter((i) => i.severity === 'critical');
    const important = allIssues.filter((i) => i.severity === 'important');
    const nice = allIssues.filter((i) => i.severity === 'nice-to-have');

    if (critical.length) {
      md += `## 🔴 Critical (${critical.length})\n\n`;
      critical.forEach((issue) => {
        md += `### ${issue.title}\n${issue.description}\n`;
        if (issue.file) md += `**File:** \`${issue.file}${issue.line ? `:${issue.line}` : ''}\`\n`;
        if (issue.suggestion) md += `**Suggestion:** ${issue.suggestion}\n`;
        if (issue.codeExample) md += `\`\`\`\n${issue.codeExample}\n\`\`\`\n`;
        md += '\n';
      });
    }

    if (important.length) {
      md += `## 🟡 Important (${important.length})\n\n`;
      important.forEach((issue) => {
        md += `### ${issue.title}\n${issue.description}\n`;
        if (issue.file) md += `**File:** \`${issue.file}\`\n`;
        if (issue.suggestion) md += `**Suggestion:** ${issue.suggestion}\n`;
        md += '\n';
      });
    }

    if (nice.length) {
      md += `## 🟢 Nice-to-have (${nice.length})\n\n`;
      nice.forEach((issue) => {
        md += `### ${issue.title}\n${issue.description}\n`;
        if (issue.suggestion) md += `**Suggestion:** ${issue.suggestion}\n`;
        md += '\n';
      });
    }

    md += `---\n\n*Generated by CodeVibes*`;
    return md;
  };

  const handleDownload = () => {
    const markdown = generateMarkdown();
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codevibes-${repoInfo?.name || 'report'}-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  if (allIssues.length === 0 && !repoInfo) {
    return (
      <div className="min-h-screen flex flex-col bg-background">
        <Header />
        <main className="flex-1 flex items-center justify-center">
          <div className="text-center animate-fade-in">
            <div className="w-20 h-20 rounded-2xl bg-card border border-border flex items-center justify-center mb-6 mx-auto">
              <FileText className="w-10 h-10 text-muted-foreground" />
            </div>
            <h1 className="text-2xl font-bold tracking-tight mb-2">No Results Yet</h1>
            <p className="text-muted-foreground mb-6">Run an analysis first to see your report.</p>
            <Button onClick={() => navigate('/analyze')} className="bg-primary hover:bg-primary/90">
              Go to Analysis
              <ArrowRight className="ml-2 w-4 h-4" />
            </Button>
          </div>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main className="flex-1 py-10">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Header */}
          <div className="mb-10 animate-slide-up">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="w-2 h-2 rounded-full bg-success" />
                  <span className="text-sm text-success font-medium">Analysis Complete</span>
                </div>
                <h1 className="text-3xl font-bold tracking-tight mb-1">{repoInfo?.name || 'Analysis Report'}</h1>
                <p className="text-muted-foreground">{repoInfo?.fullName}</p>
              </div>
              <div className="flex gap-3">
                <Button variant="outline" onClick={handleCopy}>
                  {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                  {copied ? 'Copied' : 'Copy'}
                </Button>
                <Button onClick={handleDownload} className="bg-primary hover:bg-primary/90">
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
              </div>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
              <div className="col-span-2 md:col-span-1 flex justify-center p-4 rounded-xl border border-border bg-card">
                <VibeScoreGauge score={vibeScore} size="sm" showLabel={false} />
              </div>
              <div className="p-4 rounded-xl border border-border bg-card text-center">
                <FileText className="w-5 h-5 text-muted-foreground mx-auto mb-2" />
                <div className="font-mono font-semibold text-lg">{filesScanned}</div>
                <div className="text-xs text-muted-foreground">Files Scanned</div>
              </div>
              <div className="p-4 rounded-xl border border-border bg-card text-center">
                <div className="w-2 h-2 rounded-full bg-primary mx-auto mb-2" />
                <div className="font-mono font-semibold text-lg text-primary">{allIssues.filter((i) => i.severity === 'critical').length}</div>
                <div className="text-xs text-muted-foreground">Critical</div>
              </div>
              <div className="p-4 rounded-xl border border-border bg-card text-center">
                <Clock className="w-5 h-5 text-muted-foreground mx-auto mb-2" />
                <div className="font-mono font-semibold text-lg">{formatTime(elapsedTime)}</div>
                <div className="text-xs text-muted-foreground">Time</div>
              </div>
              <div className="p-4 rounded-xl border border-border bg-card text-center">
                <Coins className="w-5 h-5 text-muted-foreground mx-auto mb-2" />
                <div className="font-mono font-semibold text-lg text-success">${((totalTokensUsed / 1000000) * 0.14).toFixed(4)}</div>
                <div className="text-xs text-muted-foreground">Cost</div>
              </div>
            </div>
          </div>

          {/* Filter Tabs */}
          <div className="flex items-center gap-1 mb-6 overflow-x-auto pb-2 border-b border-border">
            {(['all', 'critical', 'important', 'nice-to-have'] as FilterType[]).map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={cn(
                  'px-4 py-2.5 text-sm font-medium whitespace-nowrap transition-all relative',
                  filter === f
                    ? 'text-foreground'
                    : 'text-muted-foreground hover:text-foreground'
                )}
              >
                <span className="flex items-center gap-2">
                  {f === 'critical' && <span className="w-1.5 h-1.5 rounded-full bg-primary" />}
                  {f === 'important' && <span className="w-1.5 h-1.5 rounded-full bg-warning" />}
                  {f === 'nice-to-have' && <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground" />}
                  {f === 'all' ? `All (${allIssues.length})` :
                    f === 'critical' ? `Critical (${allIssues.filter((i) => i.severity === 'critical').length})` :
                      f === 'important' ? `Important (${allIssues.filter((i) => i.severity === 'important').length})` :
                        `Nice-to-have (${allIssues.filter((i) => i.severity === 'nice-to-have').length})`}
                </span>
                {filter === f && (
                  <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary rounded-full" />
                )}
              </button>
            ))}
          </div>

          {/* Issues */}
          <div className="space-y-4">
            {filteredIssues.length === 0 ? (
              <div className="text-center py-16 text-muted-foreground">
                No issues found for this filter.
              </div>
            ) : (
              filteredIssues.map((issue, index) => (
                <div
                  key={issue.id}
                  className="animate-fade-in"
                  style={{ animationDelay: `${index * 50}ms` }}
                >
                  <IssueCard issue={issue} />
                </div>
              ))
            )}
          </div>

          {/* Actions */}
          <div className="flex justify-center gap-4 mt-12">
            <Button
              onClick={() => { resetAnalysis(); navigate('/analyze'); }}
              className="bg-primary hover:bg-primary/90"
            >
              <RotateCcw className="w-4 h-4 mr-2" />
              Analyze Another
            </Button>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
